export interface EnvInterface {
    BASE_URL?: string,
    DEV?: boolean,
    MODE?: string,
    PROD?: boolean,
    SSR?: boolean,
    VITE_NODE_ENV?: string,
    VITE_URL?: string,
    VITE_APP_ENV?: string,
    VITE_APP_NAME?: string,
    VITE_APP_ID?: string,
    VITE_ORIGIN?: string,
    VITE_PORT?: string,
    VITE_ASSETS_DIR?: string,
    VITE_ENTRY_FILE?: string,
    VITE_RESOURCES_DIR?: string,
    VITE_LOGIN_PAGE?: string,
    VITE_PANEL_PAGE?: string,
    VITE_USE_LOADER?: string,
    VITE_LOADER_ON_CHANGE_PAGE?: string,
}